language: generic
before_install:
  - sudo apt-get update -y
  - sudo apt-get remove emacs || true
  - sudo apt-get remove emacs23 || true
  - sudo apt-get remove emacs24 || true
  - sudo apt-get remove emacs25 || true
install: sudo apt-get install -y make gforth
script:
  - make
  - make check
